<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>NetCrudStarter.OrchestratorModule</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.14"/>
        <PackageReference Include="Polly" Version="8.5.2" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\dotnet-crud-shared\dotnet-crud-shared.csproj" />
      <ProjectReference Include="..\dotnet-crud-student-module\dotnet-crud-student-module.csproj" />
      <ProjectReference Include="..\dotnet-crud-teacher-module\dotnet-crud-teacher-module.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Dto\" />
    </ItemGroup>

</Project>
